version: '3.8'

services:

  minio:
    image: 'quay.io/minio/minio:latest'
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio/:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"
    container_name: s3-minio-cont

  image-resize:
    build:
      context: ./image-resize
      dockerfile: Dockerfile
    container_name: image-resize
    env_file:
      - .env
    ports:
      - "8082:8082"
